def main():
    num = int(input('digite o numero de 1 a 7: '))

    dia_semana(num)

def dia_semana(num):

    if num == 1:
        print('Domingo')
    
    if num == 2:
        print('Segunda')
    
    if num == 3:
        print('Terça')
    
    if num == 4:
        print('Quarta')
    
    if num == 5:
        print('Quinta')
    
    if num == 6:
        print('Sexta')
    
    if num == 7:
        print('Sábado')

main()
